name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Optional: run manually too

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render site
        run: curl https://tejasfolio.onrender.com/